### ISSUE TITLE
Create a hyper-parameter scan module

### ISSUE THREAD

**Issue by infophysics** [Neutron-Calibration-in-DUNE/Blip#24]

**Comment by infophysics** [comment]
Need to add this additional module type under ml, which will run a hyper-parameter scan.

1. add extra module type in run_module.
2. add section to config file listing the hyper-parameters and their ranges/values.
3. add function for iterating over randomly selected hyper-parameters.
4. add some kind of metrics which will evaluate the performance.

**Comment by infophysics** [comment]
Preliminary hyper parameter scanning has been implemented.  The user can now add a section like the following to the config file:
```yaml
hyper_parameters:
  iterations: 10
  search_type:  'grid'
  model_parameters:
    BlipGraph:
      embedding:
        embedding_1:
          number_of_neighbors:  [5, 10]
          aggregation:          ['max', 'mean']
          embedding_mlp_layers: [[5, 10, 25, 10], [5, 25, 50, 25]]
      reduction:
        linear_output:          [128, 256, 512]
```

Only the 'grid' method has been implemented so far, which does a grid search up to either the number of possible combinations, or 'iterations', whichever is smaller.  the model_parameters section should be written identically to the model section, however the parameters should be a list of possible parameter values to search over.

In the random search mode, one will need to put some kind of search bounds for each variable, as well as its type.
